spring.application.name=ProyectoSpringBoot
spring.datasource.url=jdbc:mysql://localhost:3306/pesca_bd
spring.datasource.username=root
spring.datasource.password=renaido

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
